
version: '3'

services:
    flask-app:
        container_name: flask-app
        build: app
        restart: always
        ports:
            - '5000:5000'
        volumes:
            - ./app:/app
        networks:
            - backend

    mysql-db:
        container_name: mysql-db
        image: mariadb:10.3.9
        restart: always
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=teia
        ports:
            - '3308:3306'
        volumes:
            - database:/var/lib/mysql
        networks:
            - backend

networks:
    backend:

volumes:
    app:
    database:
